[[openfhe_julia]]
arch = "aarch64"
git-tree-sha1 = "ae8d6408c812c301ebed14d2dcb2b86b983989c3"
julia_version = "1.10.0"
os = "macos"

    [[openfhe_julia.download]]
    sha256 = "f28e2ed6ef89b04096449e3fcb310d34bbbce25272bad69dadac8e3af15bcec3"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.6.2+0/openfhe_julia.v0.6.2.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[openfhe_julia]]
arch = "aarch64"
git-tree-sha1 = "a826ddc9df12d2d781dbb0ab7477685fb2889629"
julia_version = "1.11.1"
os = "macos"

    [[openfhe_julia.download]]
    sha256 = "32a47bbd9ae5c3501dd6185c8729dbda633602c2b76b6d1077ab6cd4a2114bcb"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.6.2+0/openfhe_julia.v0.6.2.aarch64-apple-darwin-julia_version+1.11.1.tar.gz"
[[openfhe_julia]]
arch = "aarch64"
git-tree-sha1 = "a65f975d43e8769aad417e681ab19b2b09bdb54a"
julia_version = "1.12.0"
os = "macos"

    [[openfhe_julia.download]]
    sha256 = "d0f3a354c13bd839db306093e402f724973ee3e11f5e742451c4f1c8bd4c0d15"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.6.2+0/openfhe_julia.v0.6.2.aarch64-apple-darwin-julia_version+1.12.0.tar.gz"
[[openfhe_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff52adc000677e51408d02178d5a91faa0e1dcca"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[openfhe_julia.download]]
    sha256 = "b38f95b4bd5d98fb811404b17880de33305f0b3524a0b37604768f7875603725"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.6.2+0/openfhe_julia.v0.6.2.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[openfhe_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a20e706bfd4ccf16a81e415de02278b3edacef5"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[openfhe_julia.download]]
    sha256 = "a955aafb0b74d7934af10f189cd5aaf12db4e763f6b4126306e0731d86fbeff0"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.6.2+0/openfhe_julia.v0.6.2.aarch64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[openfhe_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4d2e4f92ead9d3f29dbcdb04cfdabe6d89d8c34"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[openfhe_julia.download]]
    sha256 = "371d31283069cde8cd7ba30a7714f38c364943b2715131b139c785dc5ced0d82"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.6.2+0/openfhe_julia.v0.6.2.aarch64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[openfhe_julia]]
arch = "x86_64"
git-tree-sha1 = "90f5841914f411d0fa6eed44fe15ac67243142e5"
julia_version = "1.10.0"
os = "macos"

    [[openfhe_julia.download]]
    sha256 = "8a1050417b2dc61e5b098ef0bce894c4956fd3a8ef5b83ae13a06325fd5a4eec"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.6.2+0/openfhe_julia.v0.6.2.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[openfhe_julia]]
arch = "x86_64"
git-tree-sha1 = "72690bc09c0abd787c660be9240e3a4d0a8aa2a8"
julia_version = "1.11.1"
os = "macos"

    [[openfhe_julia.download]]
    sha256 = "5d075ce6f18cf54f06538240b0a02ab211ec6862fcf629cdae5a216ed102a710"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.6.2+0/openfhe_julia.v0.6.2.x86_64-apple-darwin-julia_version+1.11.1.tar.gz"
[[openfhe_julia]]
arch = "x86_64"
git-tree-sha1 = "a8b4b091381ec61487025bafc8ef83ef11076f34"
julia_version = "1.12.0"
os = "macos"

    [[openfhe_julia.download]]
    sha256 = "a3ea2867b4122ef04b849701c2d1c3ae02a2e43bfed46f7f840a9ee4782d27b7"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.6.2+0/openfhe_julia.v0.6.2.x86_64-apple-darwin-julia_version+1.12.0.tar.gz"
[[openfhe_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d70e21dd93cd194d32933dc85c497fd20960b44"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[openfhe_julia.download]]
    sha256 = "fdec272af22a9d738ff857b613050d5535a983af22cf6a2d8df564d4ac41285a"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.6.2+0/openfhe_julia.v0.6.2.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[openfhe_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "86287a26c692600a87a314c06b21706a160f7d6e"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[openfhe_julia.download]]
    sha256 = "a498e257f9e365ecf508f2ec42db6ca6a380f4765478ee384bb774bb99262e9f"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.6.2+0/openfhe_julia.v0.6.2.x86_64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[openfhe_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6033404bb5ea2e211f6e0b511a1f5e3aa86509c"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[openfhe_julia.download]]
    sha256 = "d0405f636d84a5ccab5f4cd12a7ad69f0d8c8765d41880c6a146a98b084e5526"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.6.2+0/openfhe_julia.v0.6.2.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[openfhe_julia]]
arch = "x86_64"
git-tree-sha1 = "fe6a50c1301e9b1f6c9e6a5ccded3d2ded3f172b"
julia_version = "1.10.0"
os = "freebsd"

    [[openfhe_julia.download]]
    sha256 = "8c16f62670bbb78226488797be7492dc3815545ae10cd1535b1d63cc77445f2f"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.6.2+0/openfhe_julia.v0.6.2.x86_64-unknown-freebsd-julia_version+1.10.0.tar.gz"
[[openfhe_julia]]
arch = "x86_64"
git-tree-sha1 = "93b974891dbf4ff07825129b7ffef190b14f79eb"
julia_version = "1.11.1"
os = "freebsd"

    [[openfhe_julia.download]]
    sha256 = "c1af7dd95a5b010460d785caeb9ff9060177610bb64ec7e355f01d592a23b349"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.6.2+0/openfhe_julia.v0.6.2.x86_64-unknown-freebsd-julia_version+1.11.1.tar.gz"
[[openfhe_julia]]
arch = "x86_64"
git-tree-sha1 = "6d521007ecf65a7088485ae727d7e44b09f8ab86"
julia_version = "1.12.0"
os = "freebsd"

    [[openfhe_julia.download]]
    sha256 = "ec9e536fb448667dbaec3075cfd225f5b903745dee6e4e1b48c66fa28560e87d"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.6.2+0/openfhe_julia.v0.6.2.x86_64-unknown-freebsd-julia_version+1.12.0.tar.gz"
[[openfhe_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6bb692f41033ccb2b4fdcf0a98f2355d2334397"
julia_version = "1.10.0"
os = "windows"

    [[openfhe_julia.download]]
    sha256 = "e94efdb2637b5df119ee30a8aefbe2a3b426d11972a8adc7aa0aff80c75ea3df"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.6.2+0/openfhe_julia.v0.6.2.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[openfhe_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1b22662079f89119a9e3897071fbe8faa0ba6c86"
julia_version = "1.11.1"
os = "windows"

    [[openfhe_julia.download]]
    sha256 = "9c6f61595657d2a01aeb345a85a61a69b7fe2633cf34089f6336cb45048b0158"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.6.2+0/openfhe_julia.v0.6.2.x86_64-w64-mingw32-cxx11-julia_version+1.11.1.tar.gz"
[[openfhe_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8530ff7ca570468f7ac1a4eec8f8c90b213eeafe"
julia_version = "1.12.0"
os = "windows"

    [[openfhe_julia.download]]
    sha256 = "b4dc6d7e7d32eeacc4dfcd6c3f72974d819e708c2efb722e3c5e5cb9d6439374"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.6.2+0/openfhe_julia.v0.6.2.x86_64-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
